---
- name: Playbook
  hosts: gmktec
  handlers:
    - name: Load shared handlers
      ansible.builtin.import_tasks: handlers/main.yml
  roles:
    - role: system
      tags:
        - system
    - role: llama-cpp
      tags:
        - llama-cpp
    - role: comfyui
      tags:
        - comfyui
    - role: docker
      tags:
        - containers
