---
- name: Playbook
  hosts: gmktec
  roles:
      - role: system
        tags:
            - system
      # TODO : enable this
      # - role: llama-cpp
      #   tags:
      #       - llama-cpp
      - role: docker
        tags:
            - containers
      - role: models
        tags:
            - models
