home_folder: "{{ ansible_facts['user_dir'] }}"
comfy_dir: "{{ home_folder }}/ComfyUI"
docker_compose_dir: "{{ home_folder }}/docker_compose"
# ollama_models:
#   - llama3.3:70b
#   - qwen3.6:35b
# # TODO : maybe Qwen3.6 27B ?
# # TODO : maybe a mistral model ?
# # gpt-oss ?
#   - gemma4:12b
#   - hf.co/bartowski/Qwen_Qwen3.5-9B-GGUF:Q6_K_L
#   - qwen3.5:2b
#   - qwen2.5:0.5b
# # TODO : uncensored model

# this would be used with llama-cpp
# TODO : move this in vars in the llama-cpp role ?
huggingface_models:
  - name: llama3.3-70b
    repository: bartowski/Llama-3.3-70B-Instruct-GGUF
    revision: main
    files:
      - Llama-3.3-70B-Instruct-Q4_K_M.gguf
  - name: qwen3.6-35b
    repository: bartowski/Qwen_Qwen3.6-35B-A3B-GGUF
    # Prefer a pinned commit SHA later.
    revision: main
    files:
      - Qwen_Qwen3.6-35B-A3B-Q4_K_M.gguf
      - mmproj-Qwen_Qwen3.6-35B-A3B-f16.gguf
  - name: titan-qwen2.5-0.5b
    repository: theprint/TiTan-Qwen2.5-0.5B-GGUF
    revision: main
    files:
      - TiTan-Qwen2.5-0.5B-q4_k_m.gguf
  - name: gemma4-12b
    repository: bartowski/gemma-4-12B-it-GGUF
    revision: main
    files:
      - gemma-4-12B-it-Q6_K.gguf
      - mmproj-gemma-4-12B-it-f16.gguf
  - name: qwen3.5-9b
    repository: bartowski/Qwen_Qwen3.5-9B-GGUF
    revision: main
    files:
      - Qwen_Qwen3.5-9B-Q6_K_L.gguf
      - mmproj-Qwen_Qwen3.5-9B-bf16.gguf

  - name: qwen3.5-2b
    repository: bartowski/Qwen_Qwen3.5-2B-GGUF
    revision: main
    files:
      - Qwen_Qwen3.5-2B-Q8_0.gguf
