home_folder: "{{ ansible_facts['user_dir'] }}"
comfy_dir: "{{ home_folder }}/ComfyUI"
docker_compose_dir: "{{ home_folder }}/docker_compose"

# TODO : update these sometimes ?
llama_cpp_version: b10786
llama_swap_version: v252

# TODO : maybe a mistral model ? (test mistral-small3.2 and mistralai/Devstral-Small-2-24B-Instruct-2512)
# TODO : maybe even try unsloth/Mistral-Small-4-119B-2603-GGUF with a small quantization
# TODO : try OpenLLM-France/Luciole-Instruct-1.1
# TODO : uncensored model
# TODO : Muse Glimmer

# this would be used with llama-cpp
# TODO : move this in vars in the llama-cpp role ?
huggingface_models:
  - name: llama3.3-70b
    repository: bartowski/Llama-3.3-70B-Instruct-GGUF
    revision: main
    files:
      - Llama-3.3-70B-Instruct-Q4_K_M.gguf
  - name: qwen3.6-35b
    repository: bartowski/Qwen_Qwen3.6-35B-A3B-GGUF
    # Prefer a pinned commit SHA later.
    revision: main
    files:
      - Qwen_Qwen3.6-35B-A3B-Q5_K_M.gguf
      - mmproj-Qwen_Qwen3.6-35B-A3B-f16.gguf
  - name: qwen3.6-27b
    repository: bartowski/Qwen_Qwen3.6-27B-GGUF
    revision: main
    files:
      - Qwen_Qwen3.6-27B-Q4_K_L.gguf

  - name: qwen3.6-27b-rocmfp4
    repository: plunderstruck/Qwen3.6-27B-MTP-ROCmFP4-GGUF
    revision: main
    files:
      - Qwen3.6-27B-MTP-ROCmFP4-STRIX-imatrix-embF16-headQ6.gguf
      - chat_template.jinja

  - name: qwen3.8-27b
    repository: bartowski/Qwen3.8-27B-GGUF
    revision: main
    files:
      - Qwen3.8-27B-Q5_K_L.gguf
      - mmproj-Qwen3.8-27B-f16.gguf
  - name: qwen3-coder-next
    repository: unsloth/Qwen3-Coder-Next-GGUF
    revision: main
    files:
      - Qwen3-Coder-Next-UD-Q4_K_M.gguf
  - name: gemma4-12b
    repository: bartowski/gemma-4-12B-it-GGUF
    revision: main
    files:
      - gemma-4-12B-it-Q6_K.gguf
      - mmproj-gemma-4-12B-it-f16.gguf
  - name: qwen3.5-9b
    repository: bartowski/Qwen_Qwen3.5-9B-GGUF
    revision: main
    files:
      - Qwen_Qwen3.5-9B-Q6_K_L.gguf
      - mmproj-Qwen_Qwen3.5-9B-bf16.gguf

  - name: qwen-title
    repository: Qwen/Qwen2.5-1.5B-Instruct-GGUF
    revision: main
    files:
      - qwen2.5-1.5b-instruct-q5_k_m.gguf

  - name: dolphin-mistral-24B
    repository: bartowski/cognitivecomputations_Dolphin-Mistral-24B-Venice-Edition-GGUF
    revision: main
    files:
      - cognitivecomputations_Dolphin-Mistral-24B-Venice-Edition-Q4_K_M.gguf

  - name: gemma4-26b-a4b
    repository: google/gemma-4-26B-A4B-it-qat-q4_0-gguf
    revision: main
    files:
      - gemma-4-26B_q4_0-it.gguf
      - gemma-4-26B-it-mmproj.gguf
