home_folder: "{{ ansible_user_dir }}"
comfy_dir: "{{ home_folder }}/ComfyUI"
ollama_models:
  - llama3.3:70b
  - qwen3.6:35b
# TODO : maybe Qwen3.6 27B ?
# TODO : maybe a mistral model ?
# gpt-oss ?
  - gemma4:12b
  - hf.co/bartowski/Qwen_Qwen3.5-9B-GGUF:Q6_K_L
  - qwen3.5:2b
  - qwen2.5:0.5b
# TODO : uncensored model

# this would be used with llama-cpp
huggingface_models:
  - name: llama3.3-70b
    repository: bartowski/Llama-3.3-70B-Instruct-GGUF
    revision: main
    files:
      - Llama-3.3-70B-Instruct-Q4_K_M.gguf
