- name: Upgrade installed packages
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true
    update_cache: true

- name: Remove unused dependencies
  become: true
  ansible.builtin.dnf:
    autoremove: true

- name: Install reboot detection plugin
  become: true
  ansible.builtin.dnf:
    name: dnf5-plugins
    state: present

- name: Check whether a reboot is required
  become: true
  ansible.builtin.command:
    cmd: dnf5 needs-restarting
  register: system_reboot_check
  changed_when: false
  failed_when: system_reboot_check.rc not in [0, 1]

- name: Reboot when required
  become: true
  ansible.builtin.reboot:
    msg: "Rebooting after package updates"
    reboot_timeout: 600
  when: system_reboot_check.rc == 1

- name: Install common host packages
  become: true
  ansible.builtin.dnf:
    name:
      - ca-certificates
      - curl
      - git
      - python3
      - mesa-libGL
      - glib2
      - radeontop
    state: present

- name: Enable RPM Fusion free repository
  become: true
  ansible.builtin.dnf:
    name: >-
      https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{
      ansible_facts.distribution_major_version }}.noarch.rpm
    state: present
    disable_gpg_check: true

- name: Install full FFmpeg
  become: true
  ansible.builtin.dnf:
    name: ffmpeg
    state: present


- name: Add current user to GPU groups
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - render
      - video
    append: true

- name: Configure VM sysctl settings
  become: true
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "10"
    sysctl_file: /etc/sysctl.d/90-ai-server.conf
    state: present
    sysctl_set: true
    reload: true

- name: Configure ttm shared memory list
  become: true
  ansible.builtin.copy:
    dest: /etc/modprobe/increase_amd_memory.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      options ttm pages_limit=14680064
  notify: Reboot system

- name: Install comfyui
  ansible.builtin.import_tasks: comfyui.yml
