# yaml-language-server: $schema=https://raw.githubusercontent.com/mostlygeek/llama-swap/refs/heads/main/config-schema.json

globalTTL: 120
healthCheckTimeout: 600

# uncomment this to debug
# logLevel: debug
# logToStdout: both

# TODO : test --load-mode none (equivalent of --no-mmap) for every model to test load time
# TODO : test which is better with vulkan and which is better with rocm 

models:
# if RAM is complicated on the 70B model, switch the cache type to q4_0
  llama3.3-70b:
    name: "Llama 3.3 70B Instruct"
    cmd: >-
      /usr/local/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/llama3.3-70b/Llama-3.3-70B-Instruct-Q4_K_M.gguf
      --host 127.0.0.1
      --port ${PORT}
      --ctx-size 8192
      --parallel 1
      --n-gpu-layers 999
      --flash-attn on
      --cache-type-k q8_0
      --cache-type-v q8_0
      --jinja
      --load-mode none
    ttl: 900
  qwen3.6-35b:
    name: "Qwen 3.6 35B A3B Vision"
    cmd: >-
      env LD_LIBRARY_PATH={{ home_folder }}/llama-cpp-vulkan/build-vulkan/bin
      {{ home_folder }}/llama-cpp-vulkan/build-vulkan/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/qwen3.6-35b/Qwen_Qwen3.6-35B-A3B-Q5_K_M.gguf
      --mmproj {{ home_folder }}/llama-cpp-models/qwen3.6-35b/mmproj-Qwen_Qwen3.6-35B-A3B-f16.gguf
      --host 127.0.0.1
      --port ${PORT}
      --ctx-size 32768
      --parallel 1
      --n-gpu-layers 999
      --flash-attn on
      --jinja
      --load-mode none
      --temp 1.0
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence-penalty 1.5
      --repeat-penalty 1.0
      --reasoning-budget 8192
#      --cache-type-k q8_0
#      --cache-type-v q8_0
    ttl: 900

  qwen3.6-35b-hermes:
    name: "Qwen 3.6 35B A3B Hermes"
    cmd: >-
      env LD_LIBRARY_PATH={{ home_folder }}/llama-cpp-vulkan/build-vulkan/bin
      {{ home_folder }}/llama-cpp-vulkan/build-vulkan/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/qwen3.6-35b/Qwen_Qwen3.6-35B-A3B-Q5_K_M.gguf
      --host 127.0.0.1
      --port ${PORT}
      --ctx-size 131072
      --parallel 1
      --n-gpu-layers 999
      --flash-attn on
      --jinja
      --load-mode none
      --temp 0.7
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence-penalty 1.0
      --repeat-penalty 1.0
    ttl: 3600

  qwen3.6-27b:
    name: "Qwen 3.6 27B"
    cmd: >-
      /usr/local/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/qwen3.6-27b/Qwen_Qwen3.6-27B-Q4_K_L.gguf
      --host 127.0.0.1
      --port ${PORT}
      --ctx-size 32768
      --parallel 1
      --n-gpu-layers 999
      --flash-attn on
      --cache-type-k q8_0
      --cache-type-v q8_0
      --jinja
      --load-mode none
    ttl: 120

  qwen3.6-27b-rocmfpx:
    name: "Qwen 3.6 27B ROCmFPX"
    cmd: >-
      {{ home_folder }}/llama-cpp-rocmfpx/build-strix-rocmfp4/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/qwen3.6-27b-rocmfp4/Qwen3.6-27B-MTP-ROCmFP4-STRIX-imatrix-embF16-headQ6.gguf
      --device Vulkan0
      --gpu-layers 999
      --flash-attn on
      --ctx-size 32768
      --batch-size 2048
      --ubatch-size 256
      --spec-type draft-mtp
      --spec-draft-n-max 4
      --jinja
      --chat-template-file {{ home_folder }}/llama-cpp-models/qwen3.6-27b-rocmfp4/chat_template.jinja
      --host 0.0.0.0
      --port ${PORT}

  qwen3.6-27b-rocmfpx-hermes:
    name: "Qwen 3.6 27B ROCmFPX Hermes"
    cmd: >-
      {{ home_folder }}/llama-cpp-rocmfpx/build-strix-rocmfp4/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/qwen3.6-27b-rocmfp4/Qwen3.6-27B-MTP-ROCmFP4-STRIX-imatrix-embF16-headQ6.gguf
      --device Vulkan0
      --gpu-layers 999
      --flash-attn on
      --ctx-size 131072
      --parallel 1
      --batch-size 2048
      --ubatch-size 256
      --spec-type draft-mtp
      --spec-draft-n-max 2
      --jinja
      --chat-template-file {{ home_folder }}/llama-cpp-models/qwen3.6-27b-rocmfp4/chat_template.jinja
      --host 0.0.0.0
      --port ${PORT}

  # TODO : try these qwen3.8 27B with rocmfpx ?
  qwen3.8-27b:
    name: "Qwen 3.8 27B"
    cmd: >-
      env LD_LIBRARY_PATH={{ home_folder }}/llama-cpp-vulkan/build-vulkan/bin
      {{ home_folder }}/llama-cpp-vulkan/build-vulkan/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/qwen3.8-27b/Qwen3.8-27B-Q5_K_L.gguf
      --mmproj {{ home_folder }}/llama-cpp-models/qwen3.8-27b/mmproj-Qwen3.8-27B-f16.gguf
      --host 127.0.0.1
      --port ${PORT}
      --ctx-size 32768
      --parallel 1
      --gpu-layers 999
      --flash-attn on
      --cache-type-k q8_0
      --cache-type-v q8_0
      --spec-type draft-mtp
      --spec-draft-n-max 4
      --jinja
      --load-mode none
      --temp 1.0
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence-penalty 0.0
      --repeat-penalty 1.0

  qwen3.8-27b-hermes:
    name: "Qwen 3.8 27B Hermes"
    cmd: >-
      env LD_LIBRARY_PATH={{ home_folder }}/llama-cpp-vulkan/build-vulkan/bin
      {{ home_folder }}/llama-cpp-vulkan/build-vulkan/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/qwen3.8-27b/Qwen3.8-27B-Q5_K_L.gguf
      --mmproj {{ home_folder }}/llama-cpp-models/qwen3.8-27b/mmproj-Qwen3.8-27B-f16.gguf
      --host 127.0.0.1
      --port ${PORT}
      --ctx-size 131072
      --parallel 1
      --gpu-layers 999
      --flash-attn on
      --cache-type-k q8_0
      --cache-type-v q8_0
      --spec-type draft-mtp
      --spec-draft-n-max 4
      --jinja
      --load-mode none
      --temp 1.0
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --presence-penalty 0.0
      --repeat-penalty 1.0


  qwen3-coder-next:
    name: "Qwen3 Coder Next"
    cmd: >-
      /usr/local/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/qwen3-coder-next/Qwen3-Coder-Next-UD-Q4_K_M.gguf
      --host 127.0.0.1
      --port ${PORT}
      --ctx-size 32768
      --parallel 1
      --n-gpu-layers 999
      --flash-attn on
      --cache-type-k q8_0
      --cache-type-v q8_0
      --jinja
      --load-mode none
      --temp 1.0
      --top-p 0.95
      --top-k 40
    ttl: 600
    
# TODO : mistral 24B
# TODO : bigger gemma

# TODO : if not good enough, use the Bartowski Q6_K 
  gemma4-26b-a4b:
    name: "Gemma 4 26B A4B"
    cmd: >-
      /usr/local/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/gemma4-26b-a4b/gemma-4-26B_q4_0-it.gguf
      --mmproj {{ home_folder }}/llama-cpp-models/gemma4-26b-a4b/gemma-4-26B-it-mmproj.gguf
      --host 127.0.0.1
      --port ${PORT}
      --ctx-size 65536
      --parallel 1
      --n-gpu-layers 999
      --flash-attn on
      --jinja
      --load-mode none
      --temp 1.0
      --top-p 0.95
      --top-k 64
#      --cache-type-k q8_0
#      --cache-type-v q8_0

  gemma4-12b:
    name: "Gemma 4 12B Vision"
    cmd: >-
      /usr/local/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/gemma4-12b/gemma-4-12B-it-Q6_K.gguf
      --mmproj {{ home_folder }}/llama-cpp-models/gemma4-12b/mmproj-gemma-4-12B-it-f16.gguf
      --host 127.0.0.1
      --port ${PORT}
      --ctx-size 65536
      --parallel 1
      --n-gpu-layers 999
      --flash-attn on
      --cache-type-k q8_0
      --cache-type-v q8_0
      --jinja
      --load-mode none
      --ctx-checkpoints 1
      --temp 1.0
      --top-p 0.95
      --top-k 64
      --min-p 0.0
      --presence-penalty 0.0
      --frequency-penalty 0.0
      --repeat-penalty 1.0
      --reasoning-budget 192
    ttl: 900


  gemma4-12b-image-gen:
    name: "Gemma 4 12B Image Gen"
    cmd: >-
      /usr/local/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/gemma4-12b/gemma-4-12B-it-Q6_K.gguf
      --host 127.0.0.1
      --port ${PORT}
      --ctx-size 16384
      --parallel 1
      --n-gpu-layers 999
      --flash-attn on
      --cache-type-k q8_0
      --cache-type-v q8_0
      --jinja
      --load-mode none
      --ctx-checkpoints 1
      --temp 1.0
      --top-p 0.95
      --top-k 64
      --min-p 0.0
      --presence-penalty 0.0
      --frequency-penalty 0.0
      --repeat-penalty 1.0
      --reasoning-budget 192
    ttl: 60

  qwen3.5-9b:
    name: "Qwen 3.5 9B Vision"
    cmd: >-
      /usr/local/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/qwen3.5-9b/Qwen_Qwen3.5-9B-Q6_K_L.gguf
      --mmproj {{ home_folder }}/llama-cpp-models/qwen3.5-9b/mmproj-Qwen_Qwen3.5-9B-bf16.gguf
      --host 127.0.0.1
      --port ${PORT}
      --ctx-size 65536
      --parallel 1
      --n-gpu-layers 999
      --flash-attn on
      --cache-type-k q8_0
      --cache-type-v q8_0
      --jinja
      --load-mode none
    ttl: 300
  
  dolphin-mistral-24B:
    name: "Dolphin Mistral 24B"
    cmd: >-
      /usr/local/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/dolphin-mistral-24B/cognitivecomputations_Dolphin-Mistral-24B-Venice-Edition-Q4_K_M.gguf
      --host 127.0.0.1
      --port ${PORT}
      --ctx-size 32768
      --parallel 1
      --n-gpu-layers 999
      --flash-attn on
      --load-mode none
      --cache-type-k q8_0
      --cache-type-v q8_0
      --jinja
    ttl: 300

  # qwen title is kept on cpu (--n-gpu-layers 0)
  # TODO : maybe test 4096 for ctx-size ?
  # TODO : test Q4_K_M
  # TODO : in the future, maybe use it on the npu ?
  qwen-title:
    cmd: >-
      /usr/local/bin/llama-server
      --model {{ home_folder }}/llama-cpp-models/qwen-title/qwen2.5-1.5b-instruct-q5_k_m.gguf
      --host 127.0.0.1
      --port ${PORT}
      --ctx-size 8192
      --parallel 1
      --threads 4
      --n-gpu-layers 0
      --flash-attn auto
      --jinja
      --temp 0.2
      --top-p 0.9
    ttl: 0

  comfyui_auto:
    name: "ComfyUI"
    proxy: "http://127.0.0.1:8188"
    checkEndpoint: /
    websocket:
      ignore: true
    cmd: >-
      {{ comfy_dir }}/venv/bin/python 
      {{ comfy_dir }}/comfyui-git/main.py
        --listen 127.0.0.1
        --port 8188
        --input-directory {{ comfy_dir }}/input
        --output-directory {{ comfy_dir }}/output
        --user-directory {{ comfy_dir }}/user
        --bf16-vae

  # TODO : change this to 0 ?
    ttl: 3600

hooks:
  on_startup:
    preload:
      - qwen-title

routing:
  router:
    use: matrix
    settings:
      matrix:
        vars:
          title: qwen-title
          comfy: comfyui_auto
        sets:
          image: "title & comfy & gemma4-12b-image-gen"
          llms: >-
            title & (llama3.3-70b |
            qwen3.6-35b |
            qwen3.6-27b |
            qwen3.6-27b-rocmfpx |
            qwen3-coder-next |
            gemma4-26b-a4b |
            gemma4-12b |
            qwen3.5-9b |
            dolphin-mistral-24B | 
            qwen3.6-35b-hermes | 
            qwen3.6-27b-rocmfpx-hermes |
            qwen3.8-27b |
            qwen3.8-27b-hermes)