models:
  llama3.3-70b:
    cmd: >-
      /usr/local/bin/llama-server
      --port ${PORT}
      --model {{ home_folder }}/llama-cpp-models/llama3.3-70b/Llama-3.3-70B-Instruct-Q4_K_M.gguf
      --n-gpu-layers 999