---
- name: Restart ComfyUI
  ansible.builtin.systemd_service:
    name: comfyui.service
    scope: user
    state: restarted
    daemon_reload: true
  when: not ansible_check_mode

- name: Reboot system
  become: true
  ansible.builtin.reboot:
    msg: "Rebooting after system configuration changes"
    reboot_timeout: 600
